### ISSUE TITLE
Feature request: Build artifact of whole MIW

### ISSUE THREAD

**Issue by Julian-Marco** [eclipse-tractusx/managed-identity-wallet#109]
It would be great to have a build artifact of the whole MIW on Maven Central, similar to the different EDC components, e.g. the ssi-miw-credential-client: https://central.sonatype.com/artifact/org.eclipse.tractusx.edc/ssi-miw-credential-client

This would greatly reduce the complexity when trying to build the MIW (meaning: the .jar file) from outside the main repository, since as of now, you'd have to copy the whole src-folder to the desired place in order to achieve the same result (and do this over and over again whenever a new version is avaiable).

**Comment by borisrizov-zf** [comment]
The build process currently does emit a full jar and a Docker image and a Helm chart, so I'm not sure what exactly you need. Can you elaborate?

**Comment by Julian-Marco** [comment]
@borisrizov-zf I guess I have been under the false impression that there needs to be an MIW instance for every EDC instance residing in a data space, and the way that we roll out the EDC instances for different participants is by building the connector.jar based on the public artifacts of the respective modules that we need, or to be more precise: we let the different participants do that by themselves by letting them start the docker-compose stack we prepared for them. Intuitively it would have made sense to me to do the same for the miw.jar and then automatically connect the EDC instance to its own MIW instance, but from what I understood so far there should only be a single MIW instance and every new EDC simply needs to connect to it at startup (also, unlike the EDC the MIW doesn't consist of several different modules). 

... so I guess it makes more sense to simply build the MIW once and host it somewhere, and there wouldn't be any additional value in having a public artifact of it.

**Comment by borisrizov-zf** [comment]
@Julian-Marco yes, correct. At some point self-hosted wallets will be available and they should have build artefacts for anyone to deploy.

**Comment by Julian-Marco** [comment]
Thank you. I'll close this issue for now then.
