### ISSUE TITLE
Create a new workflow to do verifications on essential part of the repo

### ISSUE THREAD

**Issue by pmoscode** [eclipse-tractusx/managed-identity-wallet#119]
Create a GH action workflow, which does some validations on:
- gradle-wrapper
- validate state of Helm chart readme

**Comment by pmoscode** [comment]
Second point is done. (validate state...) -> See #113 

The first is not.

**Comment by borisrizov-zf** [comment]
Ok, I'll add it to the next dev iteration plan.

**Comment by borisrizov-zf** [comment]
To finalize this issue, we'll have to add: https://github.com/marketplace/actions/gradle-wrapper-validation to all workflows which are using the gradle wrapper.
