### ISSUE TITLE
VC Expiration Date must be set by issuer (Portal) / CGD-410

### ISSUE THREAD

**Issue by OSchlienz** [eclipse-tractusx/managed-identity-wallet#122]
Currently VC Expiration Date is set by the Wallet; this should be moved to issuer (portal). 

The issuer wants to have the possibility to set the "expirationDate" at the moment of issuance of a credential. Therefore additionally to the default an optional value for expiration date is needed (could be ignored if issuer component is coming)

summary credential logic has also to be adapted:
- [ ] put summary credential to the lowest expiry date
- [ ] once summary expires, it has to be reissued

Refers to: https://github.com/eclipse-tractusx/portal-assets/issues/92

**Comment by nitin-vavdiya** [comment]
What should be the process of reissuing summary VC? Should it be API to reissue summary or it should be done automatically(ie. using scheduled/cron job)?

**Comment by OSchlienz** [comment]
covered by issuer component
