### ISSUE TITLE
Support standardization process for upoming releases

### ISSUE THREAD

**Issue by OSchlienz** [eclipse-tractusx/managed-identity-wallet#127]
- [x] STS interface
- [x] matching of scopes to credentials
- [x] review existing stadards regarding required changes /updates
- [x] Existing Standards: 0013, 0014, 0016, 0017, 0049, 0050, 0051

**Comment by OSchlienz** [comment]
- [ ] Review for 24.03: 0016, 0050, 0051 regarding consistency of EDC-policy expressions and credentialtype (important: policy scopes will be matched to VCs for VP generation in the VP-flow. See also: https://github.com/eclipse-tractusx/ssi-docu/blob/main/docs/architecture/policy_credentialtype_scope.md
- [ ] possible standards for 24.05: scope matching, presentation flow, 
- [ ] 0051 possibly obsolete in 24.05 when summary credential is not needed anymore

**Comment by MehrdadSalari** [comment]
@borisrizov-zf tag me please
