### ISSUE TITLE
VC-Bundling / CGD-315

### ISSUE THREAD

**Issue by OSchlienz** [eclipse-tractusx/managed-identity-wallet#128]
At the moment Verifiable Presentations are limited at the moment to only one Verifiable Credential per VP; for the future the possibility to cover multiple Verifiable Credentials in a Presentation has to be supported.

Refers to: https://github.com/eclipse-tractusx/tractusx-edc/issues/656

**Comment by DominikPinsel** [comment]
Tested on MIW `v0.3.0`

1. Get Summary Credential from Wallet
2. Put Summary Credential two times into same Verifiable Presentation
3. Validate Summary Credential
  3.1 Success


As it is working I will close this issue.

@borisrizov-zf  @OSchlienz FYI
