### ISSUE TITLE
Mapping of scopes to credentials

### ISSUE THREAD

**Issue by OSchlienz** [eclipse-tractusx/managed-identity-wallet#130]
## What

The EDC will provide a string with the required scopes for a VP, which will be derived from the EDC policies. This information has to match to the VCs to be used for generating the requested VP.  

e.g. org.eclipse.tractusx.vc.type:PcfCredential_0.4.2:read.

For details: https://github.com/eclipse-tractusx/ssi-docu/blob/main/docs/architecture/policy_credentialtype_scope.md

Info on credential and policy profiles: https://github.com/eclipse-tractusx/tractusx-profiles/?tab=readme-ov-file

- Samples for credentials: https://github.com/eclipse-tractusx/tractusx-profiles/tree/main/cx/credentials/samples
- Policy definitions: https://github.com/eclipse-tractusx/tractusx-profiles/blob/main/cx/policy/specs/policy.definitions.md
- Policy mapping: https://github.com/eclipse-tractusx/tractusx-profiles/blob/main/cx/policy/specs/policy.mapping.md

Mapping credential type --> VC as first step, contract version will be checked on EDC-side policy check.

related to: 
https://github.com/eclipse-tractusx/sig-release/issues/248

**Comment by borisrizov-zf** [comment]
Task outline for VP scope matching and VP endpoint:

- [ ] miw: add a new route to the presentation controller (for VP with si token)
- [ ] miw: create custom web filter to validate si token header for this request
- [ ] miw: parsing of scopes
