### ISSUE TITLE
Security evaluation of VP flow & STS approach

### ISSUE THREAD

**Issue by OSchlienz** [eclipse-tractusx/managed-identity-wallet#132]
## What
The VP flow and the concept of the Secure Token Service have to pass a security evaluation.

related to:
https://github.com/eclipse-tractusx/sig-release/issues/248

**Comment by Essenbreis** [comment]
Hi Oliver, we do you have time to start the security evaluation. I asked @pablosec  and @SSIRKC for help .

**Comment by SSIRKC** [comment]
Hi @OSchlienz @Essenbreis,
to evaluate the concept I would kindly ask for more details about the authentication flow. 
Who is the authorizing party and what kind of token concept is used and what are the specifics you are planning?

Looking at your description:
"The secure token service is a mechanism to obtain a token for access to the wallet - including a control mechanism to specify which certificates can be queried with this interface"
A standard web token based session management is plannend. Correct?

Helpful would be to know:

- The session management framework used
- Lifetime/expiration
- Invalid token handling
- Session ID length
- token exchange transport encryption used

**Comment by OSchlienz** [comment]
An overarching security review of the VPP concept was done for R24.05; MIW was not in scope of this review.
