### ISSUE TITLE
QG 4 & 5 Preparation

### ISSUE THREAD

**Issue by OSchlienz** [eclipse-tractusx/managed-identity-wallet#135]
## What
Criteria from Release Mgmt. to be fulfilled:
- for Q-Gate 4  before 24.11.
- Compliance: https://github.com/eclipse-tractusx/sig-release/issues/101
- Documentation: https://github.com/eclipse-tractusx/sig-release/issues/102
- Security: https://github.com/eclipse-tractusx/sig-release/issues/103
- Test-Results: https://github.com/eclipse-tractusx/sig-release/issues/104
- for Q-Gate 5 before 07.12.

link to tracking board: 
- [x] schedule necessary meetings (threat-analysis, test-mgmgt, security scans, gdpr, gaia-x, interoperability, data sovereignity)
- [x] organize gate reviews

**Comment by mknoopvw** [comment]
Can you please supply detailed information on the Q-Gates?

**Comment by mknoopvw** [comment]
@mknoopvw see

- [ ]  https://github.com/eclipse-tractusx/sig-release/issues/103
