### ISSUE TITLE
W3C Caused by: com.apicatalog.jsonld.JsonLdError: Unexpected response code [429]

### ISSUE THREAD

**Issue by tuanphampmt** [eclipse-tractusx/managed-identity-wallet#138]
My name is Tuan, I am getting the following error:

```
Caused by: com.apicatalog.jsonld.JsonLdError: Unexpected response code [429].
JsonLdError[code=There was a problem encountered loading a remote context [code=LOADING_REMOTE_CONTEXT_FAILED]., message=There was a problem encountered loading a remote context [code=LOADING_REMOTE_CONTEXT_FAILED].]
```

According to my understanding of this error, I seem to have sent many requests to two urls:

```
"https://www.w3.org/2018/credentials/v1",
"https://catenax-ng.github.io/product-core-schemas/SummaryVC.json",

```
Can I ask if the w3.org organization seems to have limited my request?
Can you help me solve this problem? I really need help to complete my work
Sincerely thank

**Comment by borisrizov-zf** [comment]
Hi Tuan,

please in the future supply more information about the MIW version you're trying to use.

I'm assuming you're on something < 0.2.0. There was an issue with rate-limiting which is now solved. Please use the current 0.2.0 or later.
