### ISSUE TITLE
TRG 1.03 appropriate `CHANGELOG.md`

### ISSUE THREAD

**Issue by carslen** [eclipse-tractusx/managed-identity-wallet#151]
Our TRG  recomments to follow the [keep a changelog format](https://keepachangelog.com/de/1.0.0/) but it's not mandatory (_format **should** follow the format_), but you don't.

Please consider to follow the format (_Unreleased_, _Added_, _Changed_, etc.) to have consistent `CHANGELOG.md` files accross eclipse-tractusx.

**Comment by borisrizov-zf** [comment]
The CHANGELOG is being correctly formatted since 0.2.0
