### ISSUE TITLE
TRG 6.01 Released Helm Chart

### ISSUE THREAD

**Issue by carslen** [eclipse-tractusx/managed-identity-wallet#156]
Helm chart for product MIW is released but not as seperate GH release, but within the main release workflow. As a result there is no GH release for the Helm chart available, althoug it's released and available in Helm repository.

Needs clarification if this is acceptable, althoug this approach is violating [TRG 6.01 - Released Helm Chart](https://eclipse-tractusx.github.io/docs/release/trg-6/trg-6-1):

![grafik](https://github.com/eclipse-tractusx/managed-identity-wallet/assets/28647218/d19e203d-13fa-4ab2-b61a-064cee585a29)

This is not a blocking issue, but shall be used for clarification and/or overthinking TRG 6.01.

/cc @Siegfriedk

**Comment by Siegfriedk** [comment]
We use a gh release + tag as its best practise and stores the artifact in time. Yes to a proper gh release but the minimum is a tag

**Comment by borisrizov-zf** [comment]
Resolved via #222
