### ISSUE TITLE
TRG 7.01 Legal Documentation

### ISSUE THREAD

**Issue by carslen** [eclipse-tractusx/managed-identity-wallet#167]
## NOTICE.md / DEPENDENCIES / 3rd party libs
https://github.com/eclipse-tractusx/managed-identity-wallet/blob/287b61d12cabf7e2a39f60e1f49d9baaa8401e8c/NOTICE.md?plain=1#L39-L44

Notice is outdated, as you're using cx-ssi-lib:0.0.17 according to your `buildd.gradle` file:

https://github.com/eclipse-tractusx/managed-identity-wallet/blob/287b61d12cabf7e2a39f60e1f49d9baaa8401e8c/build.gradle#L82

Now there are 3 problems:
- version mismatch (version mentioned in NOTICE.md and really used version)
- there is a [eclipse-tractusx/SSI-agent-lib](https://github.com/eclipse-tractusx/SSI-agent-lib) repo, why isn't it used in this release?
- the [catenax-ng/product-lab-ssi](https://github.com/catenax-ng/product-lab-ssi) repository is used instead:
  https://github.com/eclipse-tractusx/managed-identity-wallet/blob/287b61d12cabf7e2a39f60e1f49d9baaa8401e8c/build.gradle#L47-L52
  This repo does not match open-source criteria (e.g. missing DEPENDENCIES at top level, just as an example) and is not monitored actively by Eclipse-Tractus-X mechanisms (e.g. [Release Guidelines Checks](https://eclipse-tractusx.github.io/sig-release/)) as it belongs to Cantena-X consortia.

The most problematic issue is, that we're using a 3rd party lib which is not well maintained and not apply to Eclipse guidelines nor to our TRGs.

This needs clarification and is a potential blocker for QG4 aproval.

**Comment by borisrizov-zf** [comment]
Hi Carsten,

I'll try to address all mentioned issues.

The version mismatch is an oversight on our side, but we'll fix that ASAP.

The root cause of the rest of the issues is exactly that the catenax-ng repo is not compliant, so we had to move the code to tractus-x. In the meantime we've fixed most of the compliance issues, and are working on adding the Maven Central release workflow. We cannot use the tractus-x repo until this is done, as it doesn't have a release mechanism and we didn't want to implement the GitHub release, just to throw it away later in favour of the Maven Central release.

I hope this clarifies the whole thing a bit. Our plan is to have the tractus-x repo ready by the time we release the new version of the MIW.

**Comment by carslen** [comment]
It is mandatory to release the cx-ssi-lib in eclipse-tractusx for release 23.12, as we're preparing already the next release. 

@AngelikaWittek

**Comment by borisrizov-zf** [comment]
I've prepared the maven release workflow, I'll assign you as a reviewer.

One open question @carslen: how do we handle non-automatic closing of the staging maven repository? Do we just always automatically close it and directly release to Maven Central?

**Comment by carslen** [comment]
Aligned on the following steps:
- prepare the eclipse-tractusx/cx-ssi-lib repopsitory to be able topublish the ssi-lib 
- publish the required package in eclipse-tractusx/cx-ssi-lib (Maven)
- eclipse-tractusx/managed-identity-wallet repository will publish a new version, most likely 0.2.1 which
  - removed the catenax-ng reference from `NOTICE.md`
  - update build process and `DEPENDENCIES` to use ssi-lib from eclipse-tractusx repository
  - include security updates to solve vulnerabilities

**Comment by carslen** [comment]
Any progress here? Please provide update @borisrizov-zf @OSchlienz

**Comment by borisrizov-zf** [comment]
@carslen You've already noticed some of the work being done.

- [x] prepare the eclipse-tractusx/cx-ssi-lib repopsitory to be able topublish the ssi-lib
- [x] publish the required package in eclipse-tractusx/cx-ssi-lib (Maven)
- [x] removed the catenax-ng reference from NOTICE.md (PR in review)
- [x] update build process and DEPENDENCIES to use ssi-lib from eclipse-tractusx repository (PR in review)
- [ ] include security updates to solve vulnerabilities: will resolve this in the 0.0.18 version of the cx-ssi-lib, as we can publish more frequently now.

**Comment by borisrizov-zf** [comment]
@carslen all tasks here are done, you can do a final check and close.

**Comment by borisrizov-zf** [comment]
@carslen Release 0.3.0 is out now. I left another comment about the other issue.

**Comment by carslen** [comment]
Topics of this issue has been solved.
