### ISSUE TITLE
TRG 7.05 Legal information for distributions

### ISSUE THREAD

**Issue by carslen** [eclipse-tractusx/managed-identity-wallet#171]
As a published Docker Container is a distribution, legal documentation must be added to the container.

Proposal for your Dockerfile:

```dockerfile
[...]
COPY LICENSE NOTICE.md DEPENDENCIES /build/libs/miw-latest.jar /app/

WORKDIR /app

[...]
```

This will place the legal documentation next to your application jar file. The jar itself already contains the legal docs in `META-INF` 👍.

**Comment by borisrizov-zf** [comment]
Done with PR #183
