### ISSUE TITLE
Remove v1.1.0 from chart index.yaml

### ISSUE THREAD

**Issue by fty4** [eclipse-tractusx/managed-identity-wallet#204]
Hello,

I am not sure why there is a release `v1.1.0` in the Helm releases:

https://github.com/eclipse-tractusx/managed-identity-wallet/blob/e7b2ae011b15f35e07d59b428c461fd8add7e0d9/index.yaml#L4-L41

Shouldn't that be removed because the new versioning is now at `v0.3.0`?

When searching for repos with Helm that might also lead to confusion:

```bash
$ helm search repo tractusx-dev/managed-identity-wallet --versions
NAME                                    CHART VERSION   APP VERSION     DESCRIPTION                                       
tractusx-dev/managed-identity-wallet    1.1.0           0.0.1           Managed Identity Wallet is supposed to supply a...
tractusx-dev/managed-identity-wallet    0.3.0           0.3.0           Managed Identity Wallet is supposed to supply a...
```

<hr />

<sub>Marco Lecheler [marco.lecheler@mercedes-benz.com](mailto:marco.lecheler@mercedes-benz.com) Mercedes-Benz Tech Innovation GmbH ([ProviderInformation](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md))</sub>

**Comment by SebastianBezold** [comment]
Hey @borisrizov-zf,

since i'm not sure, which of these versions are needed/used, could you please clarify.
If there are any versions listed in our tractusx charts repo that are not needed anymore, I can remove them for you.

**Comment by borisrizov-zf** [comment]
Yes, I saw that while updating TRG 5.09. @SebastianBezold what would the correct procedure be? Just delete the file from the `gh-pages` branch? Do you have to do something on your side?

**Comment by fty4** [comment]
The `tgz`-file is not present in the [`gh-pages`](https://github.com/eclipse-tractusx/managed-identity-wallet/tree/gh-pages/helm-charts) branch - therefore it might be better to just remove the version from the [`index.yaml`](https://github.com/eclipse-tractusx/managed-identity-wallet/blob/gh-pages/index.yaml) file?

I just validated this - the [command](https://github.com/eclipse-tractusx/managed-identity-wallet/blob/01a70fd2659893d4d5f28da160ab84b778386a12/.github/workflows/release.yml#L224C54-L224C123) generating the Helm repo index.yaml does not recreate the version 1.1.0.
Therefore it might be the best option to just remove the list item from the yaml - I will create a PR for that.
