### ISSUE TITLE
Feature: add puris framework agreement

### ISSUE THREAD

**Issue by tom-rm-meyer-ISST** [eclipse-tractusx/managed-identity-wallet#232]
**Problem**
Currently only the framework agreements listed by [ssi-docu](https://github.com/eclipse-tractusx/ssi-docu/blob/main/docs/architecture/cx-3-2/edc/policy.definitions.md#34-resiliency) are possible. With R24.03 PURIS provides a framework agreement and participates in QGate.

**Solution**
Add a framework agreement for PURIS.

In case I need to contact further persons, please let me know.

**Comment by nitin-vavdiya** [comment]
@tom-rm-meyer-ISST 
Do you still think this issue is relevant? If not, can we consider closing it?

**Comment by tom-rm-meyer-ISST** [comment]
@nitin-vavdiya sorry missed it. Closed as not needed anymore. Also I think it was misplaced here. Thanks for pointing out!
