### ISSUE TITLE
Refactor: change field name in token response

### ISSUE THREAD

**Issue by borisrizov-zf** [eclipse-tractusx/managed-identity-wallet#295]
# Description

The iatp suggest using the field name `access_token` as the JSON response of the token endpoint. The current implementation uses `token`, but the latest version of the EDC expects `access_token`.

# Acceptance criteria

The token endpoint uses `access_token` as the field name of the JSON response

**Comment by thackerronak** [comment]
Ref: https://github.com/eclipse-tractusx/managed-identity-wallet/pull/293
