### ISSUE TITLE
Remove stale credential types

### ISSUE THREAD

**Issue by borisrizov-zf** [eclipse-tractusx/managed-identity-wallet#307]
### Description

It was noted in #260 that some credential types are no longer valid/necessary, i.a. `{"type":"ResiliencyCredential"}`.

### Acceptance Criteria

- [x] All stale/unnecessary credential types are removed from the business logic
- [x] All stale/unnecessary credential types are removed from tests 
- [x] All stale/unnecessary credential types are removed from docs

**Comment by nitin-vavdiya** [comment]
Fixed with: https://github.com/eclipse-tractusx/managed-identity-wallet/pull/315
