### ISSUE TITLE
[TRG 4.05 - Container Registries] Publish Docker image on hub.docker.com

### ISSUE THREAD

**Issue by carslen** [eclipse-tractusx/managed-identity-wallet#34]
Adjust your workflows for docker image build to publish image on Docker Hub, please refer to [TRG 4.05 - Container Registries](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-05).

https://github.com/eclipse-tractusx/managed-identity-wallet/blob/93f9ade777fde3a081636790b8152aa32b50dc5b/.github/workflows/service-build.yaml#L8-L10

Please ensure to tag your docker image to match requirements from [TRG 4.01 - Image Tagging](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-01).

**Comment by DominikPinsel** [comment]
After this is done enable chart lint testing again in `chart-lint.yml`

**Comment by SebastianBezold** [comment]
I can currently not find any docker image build + publish workflow. I also cannot find a released image on DockerHub yet. This is blocking #53
