### ISSUE TITLE
fix: build docker image in the helm test workflow

### ISSUE THREAD

**Issue by almadigabor** [eclipse-tractusx/managed-identity-wallet#51]
Please modify your workflow like in [this example](https://github.com/eclipse-tractusx/item-relationship-service/blob/main/.github/workflows/helm-test.yaml#L37) so the app image is built in the workflow. With this approach unreleased app version still in development (like in #48) won't be a problem while running helm test.

**Comment by pmoscode** [comment]
Hi @almadigabor,
can be closed now.

**Comment by SebastianBezold** [comment]
Can confirm. Closing the issue
