### ISSUE TITLE
`helm test` workflow should have kind node tag input

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/managed-identity-wallet#68]
## Description 

The helm test workflow already verifies, that the Chart can successfully be installed on a kind cluster.
It should additionally have an input for the `kindest/node` image used by kind, so different Kubernetes API versions can be tested on demand

See [TRG 5.09](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-09) for an example of such an input variable

found during #53

**Comment by borisrizov-zf** [comment]
Will add this to next dev iteration.
