### ISSUE TITLE
Add `helm upgrade` workflow/step

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/managed-identity-wallet#69]
[TRG 5.11](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-11) requires for an upgradeability check of our Charts.
Meaning, that we should test, if `helm upgrade` succeeds when upgrading from the latest release version of the Chart to the current Chart and configuration present in the repository.

You can see the last step of the workflow shown in [TRG 5.09](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-09) for an example

found during #53

**Comment by mknoopvw** [comment]
@pmoscode let's have a look at it once there is time to do so.

**Comment by borisrizov-zf** [comment]
This has been resolved.
