### ISSUE TITLE
Vault Concept for key storage in MIW / CGD-246, CGD-418

### ISSUE THREAD

**Issue by OSchlienz** [eclipse-tractusx/managed-identity-wallet#86]
Refers to CGD-246, CGD-418:
At the moment Private Keys are AES encrypted stored in the MIW Postgres Database; For the a vault concept for PK storage should be developed and implemented 

- Hashicorp vault to be used
- secrets engine. to be selected

**Comment by PManaras** [comment]
A secure storage for private keys, separated for each tenant/wallet could be realized via following approaches:

# MIW - Direct Access

* save the keys in vault
* MIW retrieves key of the corresponding tenant/wallet from vault

## Downsides:

MIW can access all keys directly

# Crypto Service

* Implementing a crypto service that is started for each tenant
* wallet communicates via REST with crypto service to create proofs for VP
* crypto service is able to retrieve the corresponding private key of the tenant/wallet to execute crypto operations
* MIW has only access to the crypto service and not the vault itself
* unique secret for the access to the vault for each crypto service 

## variants:

1. save encryption key and encrypt the private keys in DB (current approach, but for each service in personal DB)
2. save the actual keys in the vault
3. use vault for PVC encryption (Key Management Service needed, which is HashiCorp Vault able to provide)
