### ISSUE TITLE
Make liveness & readiness probes configurable

### ISSUE THREAD

**Issue by florianrusch-zf** [eclipse-tractusx/managed-identity-wallet#98]
As the title points out, it's at the moment not possible to configure liveness & readiness probes. E.g. if you reduce the CPU resources for the MIW it can happen, that it's not fully booted in the preconfigured timeouts.

**Comment by borisrizov-zf** [comment]
Great addition, as soon as we are done getting the develop branch up-to-speed, we can get this in.
